#### Consider the below code to answer further questions:

In [1]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [3]:
type(list_[0])

str

In [4]:
type(array_list)

numpy.ndarray

* Yes as we could see that there is a difference between a Variable list and array_list for the datatype, because when we try to pass a list inside and `np.array` the list is converted to an array. 

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list

In [5]:
def data_type(list_):
    
    for x in list_:
        if isinstance(x, int):
            print("It is an integer")
        if isinstance(x, str):
            print("It is an string")
        if isinstance(x, float):
            print("It is a float")

data_type(list_)

It is an string
It is an string
It is an string
It is an string
It is an string


In [6]:
array_list.dtype

dtype('<U1')

* dtype('<U1') it simply says that elements in numpy array are unicode of strings with length of 1

#### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list

In [7]:
array_list = np.array(list_,dtype = int)

In [8]:
list_ = [1,2,3,4,5]

In [9]:
array_list

array([1, 2, 3, 4, 5])

In [10]:
for i in list_:
    print(type(i))
    
for i in array_list:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Q4. Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [11]:
num_list = [[1,2,3],[4,5,6]]

In [12]:
num_array = np.array(object = num_list)

In [13]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
num_array.shape ### Shape will provide the number of rows and columns inside an array

(2, 3)

In [15]:
num_array.size ### Size will provide you the number of elements present inside an array.

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [16]:
zeros = np.zeros((3,3))

In [17]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
zeros.size

9

In [19]:
zeros.shape

(3, 3)

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [20]:
Identity_Matrix = np.eye(5)

In [21]:
Identity_Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
Identity_Matrix.shape

(5, 5)